# Generated by Django 4.1 on 2022-11-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("t_test_app", "0003_userinput_delete_entryone_delete_entrytwo"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinput", name="input_one",),
        migrations.RemoveField(model_name="userinput", name="input_two",),
    ]
